# Generated by Django 5.1.4 on 2025-01-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_feeding_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feeding",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="feeding",
            old_name="at",
            new_name="cat",
        ),
    ]
