# Generated by Django 5.1.5 on 2025-01-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_toy"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="toys",
            field=models.ManyToManyField(to="main_app.toy"),
        ),
        migrations.AlterField(
            model_name="toy",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
